/**
 * AI Planner — Streaming Engine
 *
 * Executes the planner pipeline in 8 real stages, emitting live events as each
 * stage completes. Every event corresponds to actual execution work — no fake
 * timers, no artificial delays.
 *
 * Stage → Section mapping (sections generated by the LLM):
 *   Stage 1  Analyze Request      — message parsing, API key check, setup
 *   Stage 2  Classify Project     — intent classification (regex + optional LLM)
 *   Stage 3  Design Architecture  — LLM sections 1–5
 *   Stage 4  Design Database      — LLM section 6
 *   Stage 5  Generate APIs        — LLM sections 7–8
 *   Stage 6  Security Review      — LLM section 9
 *   Stage 7  Deployment Strategy  — LLM sections 10–12
 *   Stage 8  Blueprint Finalization — stream complete, content assembled
 */

const OPENROUTER_URL = "https://openrouter.ai/api/v1/chat/completions";
const TIMEOUT_MS = 120_000;

const PLANNER_MODELS = [
  "moonshotai/kimi-k2",
  "deepseek/deepseek-chat-v3-0324",
  "openai/gpt-oss-20b:free",
] as const;

type PlannerModel = (typeof PLANNER_MODELS)[number];

// ── Exported constants ─────────────────────────────────────────────────────────

export const PLANNER_STAGES = [
  { id: 1, name: "Analyze Request" },
  { id: 2, name: "Classify Project" },
  { id: 3, name: "Design Architecture" },
  { id: 4, name: "Design Database" },
  { id: 5, name: "Generate APIs" },
  { id: 6, name: "Security Review" },
  { id: 7, name: "Deployment Strategy" },
  { id: 8, name: "Blueprint Finalization" },
] as const;

// Which stage a given section number (1–12) maps to
const SECTION_TO_STAGE: Record<number, number> = {
  1: 3, 2: 3, 3: 3, 4: 3, 5: 3,
  6: 4,
  7: 5, 8: 5,
  9: 6,
  10: 7, 11: 7, 12: 7,
};

// ── Event types ────────────────────────────────────────────────────────────────

export type PlannerStreamEvent =
  | { type: "stage_start"; stage: number; name: string }
  | { type: "stage_complete"; stage: number }
  | { type: "content_chunk"; text: string }
  | { type: "section_detected"; section: number; title: string }
  | { type: "done"; content: string; model: string }
  | { type: "conversation"; content: string }
  | { type: "error"; message: string };

// ── Helpers ────────────────────────────────────────────────────────────────────

function sanitizeKey(value: string | undefined): string | undefined {
  if (!value) return undefined;
  const cleaned = value.replace(
    /^[\s\u00A0\u200B\u200C\u200D\uFEFF\r\n]+|[\s\u00A0\u200B\u200C\u200D\uFEFF\r\n]+$/g,
    "",
  );
  return cleaned || undefined;
}

export interface PlannerStreamMessage {
  role: string;
  content: string;
}

// ── Intent classification (reused from planner.ts patterns) ───────────────────

const GREETING_START_PATTERNS: RegExp[] = [
  /^(hello|hi|hey|howdy|yo|greetings|sup|hola|ciao|bonjour|hallo|salut)\b/i,
  /^good\s+(morning|evening|afternoon|night|day)\b/i,
  /^(السلام\s*عليكم|سلام|مرحب[اً]?|أهل[اً]?|اهل[اً]?|صباح\s*الخير|مساء\s*الخير|هلا|هاي)/u,
];

const CASUAL_PATTERNS: RegExp[] = [
  /\bhow\s+are\s+you\b/i,
  /\bwho\s+are\s+you\b/i,
  /\bwhat\s+(can|do)\s+you\b/i,
  /\bwhat\s+are\s+you\b/i,
  /^(thanks|thank\s+you|thx|ty|cheers|great|nice|cool|awesome|perfect|good)\b/i,
  /^(ok|okay|sure|alright|got\s+it|i\s+see|understood)\b/i,
];

const PROJECT_ACTION_PATTERNS: RegExp[] = [
  /\b(build|create|make|develop|design|generate|launch|start|write|code|program|deploy|set\s*up|implement)\b/i,
  /\b(اعمل|أعمل|ابني|أبني|انشئ|أنشئ|طور|اصنع|عايز|عاوز|محتاج|ابغى)\b/u,
];

const PROJECT_TYPE_PATTERNS: RegExp[] = [
  /\b(website|web\s*app|webapp|app|application|bot|chatbot|telegram|discord|slack|whatsapp|dashboard|saas|platform|api|system|store|shop|portal|service|tool|e[-\s]?commerce|ecommerce|mobile\s*app|landing\s*page|crm|erp|cms|marketplace|forum|blog|portfolio|admin\s*panel|automation)\b/i,
  /\b(موقع|بوت|تطبيق|تيليجرام|ديسكورد|واتساب|لوحة\s*تحكم|منصة|متجر|خدمة|سيستم|موبايل|مدونة|منتدى|نظام)\b/u,
];

type IntentType = "GREETING" | "CONVERSATION" | "PROJECT" | "AMBIGUOUS";

function classifyIntentFast(message: string): IntentType {
  const trimmed = message.trim();
  const isShort = trimmed.length < 120;

  if (
    isShort &&
    GREETING_START_PATTERNS.some((p) => p.test(trimmed))
  ) return "GREETING";

  if (isShort && CASUAL_PATTERNS.some((p) => p.test(trimmed))) return "CONVERSATION";

  const hasAction = PROJECT_ACTION_PATTERNS.some((p) => p.test(trimmed));
  const hasType = PROJECT_TYPE_PATTERNS.some((p) => p.test(trimmed));
  if (hasAction && hasType) return "PROJECT";

  if (!isShort && (hasAction || hasType)) return "PROJECT";

  return "AMBIGUOUS";
}

// ── System prompts ─────────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a professional software architect and technical planner for an AI Website & Bot Builder platform.

Your role is to analyze user project requests and generate comprehensive, structured architecture plans.

CRITICAL RULES:
- Never respond as a general chatbot or assistant
- Always produce a complete, structured architecture plan with ALL 12 sections
- Be precise, professional, and actionable
- Plans must be structured for future automation by AI Coder, Designer, and DevOps modules

When a user describes a project, output a plan using EXACTLY this format:

## 1. Project Summary
A clear, concise description of the project and its primary value proposition.

## 2. Project Type
Classification: Website / Telegram Bot / Discord Bot / SaaS Platform / Dashboard / Mobile App / API Service / E-Commerce / etc.

## 3. Core Features
List all core features with brief, actionable descriptions.

## 4. Pages / Screens
For websites: list all pages and their purpose.
For bots: list all command flows, menus, and interaction states.

## 5. User Roles
Define all user types and their permissions (e.g., Guest, User, Admin, Super Admin).

## 6. Database Structure
List main data entities and their key fields. Keep it precise and structured.

## 7. API Requirements
List required internal API endpoints and external service integrations.

## 8. System Architecture
Describe the complete technical stack: frontend, backend, database, caching, queues, external services.

## 9. Security Requirements
Authentication method, authorization rules, data protection, input validation, rate limiting.

## 10. Deployment Strategy
Hosting platform, containerization, CI/CD pipeline, environment variables, scaling approach.

## 11. Development Phases
Break development into clear phases (Phase 1: MVP, Phase 2: Core, Phase 3: Advanced) with deliverables.

## 12. Future Enhancements
Features and capabilities to add after initial launch.

IMPORTANT: Always output ALL 12 sections. Be thorough but concise.`;

const CONVERSATION_SYSTEM_PROMPT = `You are a helpful, friendly AI assistant. Respond naturally and conversationally.
- Reply naturally to greetings, small talk, and casual questions
- Keep responses short and natural (1-3 sentences for simple greetings/chat)
- Never output numbered sections or structured plans for casual conversation`;

// ── OpenRouter streaming call ──────────────────────────────────────────────────

interface StreamCallResult {
  content: string;
  model: string;
}

async function callOpenRouterStream(
  model: PlannerModel,
  messages: { role: string; content: string }[],
  apiKey: string,
  onChunk: (text: string) => void,
  signal: AbortSignal,
): Promise<StreamCallResult> {
  console.log(`[MODEL_SELECTED] planner stream model=${model}`);

  const timeoutSignal = AbortSignal.timeout(TIMEOUT_MS);
  const combined = combineSignals(signal, timeoutSignal);

  let response: Response;
  try {
    response = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
        "X-Title": "AI Agent",
      },
      body: JSON.stringify({
        model,
        messages,
        stream: true,
        temperature: 0.3,
        max_tokens: 8000,
      }),
      signal: combined,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[MODEL_FAILED] planner stream model=${model} fetch error=${msg.slice(0, 120)}`);
    throw err;
  }

  console.log(`[MODEL_SELECTED] planner stream response status=${response.status} model=${model}`);

  if (!response.ok) {
    const body = await response.text().catch(() => "");
    console.error(`[MODEL_FAILED] planner model=${model} status=${response.status} body=${body.slice(0, 200)}`);
    const err = new Error(`OpenRouter ${response.status}: ${body.slice(0, 200)}`);
    (err as Error & { status: number }).status = response.status;
    throw err;
  }

  const reader = response.body?.getReader();
  if (!reader) throw new Error("No response body from OpenRouter");

  const decoder = new TextDecoder();
  let buffer = "";
  let fullContent = "";
  let resolvedModel = model;

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() ?? "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith("data: ")) continue;
        const data = trimmed.slice(6);
        if (data === "[DONE]") continue;

        try {
          const parsed = JSON.parse(data) as {
            model?: string;
            choices?: { delta?: { content?: string } }[];
          };
          if (parsed.model) resolvedModel = parsed.model as PlannerModel;
          const chunk = parsed.choices?.[0]?.delta?.content ?? "";
          if (chunk) {
            fullContent += chunk;
            onChunk(chunk);
          }
        } catch {
          // malformed SSE line — skip
        }
      }
    }
  } finally {
    reader.releaseLock();
  }

  return { content: fullContent, model: resolvedModel };
}

// Non-streaming conversational call (greetings / casual)
// Use paid models first — free-tier models queue and can hang for 30+ seconds
const CONVERSATIONAL_MODEL = "moonshotai/kimi-k2";
const CONVERSATIONAL_TIMEOUT_MS = 15_000;

// Helper: combine abort signals — AbortSignal.any is Node 20+ / modern browsers
function combineSignals(a: AbortSignal, b: AbortSignal): AbortSignal {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const anyFn = (AbortSignal as any).any as ((signals: AbortSignal[]) => AbortSignal) | undefined;
  return anyFn ? anyFn([a, b]) : b;
}

async function callOpenRouterConversational(
  messages: { role: string; content: string }[],
  apiKey: string,
  signal: AbortSignal,
): Promise<string> {
  console.log(`[MODEL_SELECTED] conversational model=${CONVERSATIONAL_MODEL}`);

  // AbortSignal.timeout is proven to work (startup validation uses it).
  // Combining with the outer signal ensures client-disconnect also aborts.
  const timeoutSignal = AbortSignal.timeout(CONVERSATIONAL_TIMEOUT_MS);
  const combined = combineSignals(signal, timeoutSignal);

  let response: Response;
  try {
    response = await fetch(OPENROUTER_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
        "X-Title": "AI Agent",
      },
      body: JSON.stringify({
        model: CONVERSATIONAL_MODEL,
        messages,
        stream: false,
        temperature: 0.7,
        max_tokens: 400,
      }),
      signal: combined,
    });
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[MODEL_FAILED] conversational model=${CONVERSATIONAL_MODEL} fetch error=${msg.slice(0, 120)}`);
    throw err;
  }

  if (!response.ok) {
    const body = await response.text().catch(() => "");
    console.error(`[MODEL_FAILED] conversational model=${CONVERSATIONAL_MODEL} status=${response.status} body=${body.slice(0, 120)}`);
    throw new Error(`OpenRouter ${response.status}: ${body.slice(0, 120)}`);
  }

  // Read body with same combined signal so hanging body also times out
  let json: { choices?: { message?: { content?: string } }[] };
  try {
    json = await response.json() as typeof json;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error(`[MODEL_FAILED] conversational model=${CONVERSATIONAL_MODEL} json error=${msg.slice(0, 120)}`);
    throw err;
  }

  const content = json.choices?.[0]?.message?.content?.trim();
  if (!content) throw new Error("empty conversational response");
  console.log(`[PLANNER_COMPLETED] conversational model=${CONVERSATIONAL_MODEL} contentLength=${content.length}`);
  return content;
}

// ── Section boundary detector ──────────────────────────────────────────────────

const SECTION_HEADER_RE = /^##\s+(\d+)\.\s+(.+)$/m;

function detectSectionInChunk(
  accumulated: string,
  lastDetectedSection: number,
): { section: number; title: string } | null {
  // Look for section headers in the accumulated text
  const lines = accumulated.split("\n");
  for (const line of lines) {
    const match = SECTION_HEADER_RE.exec(line);
    if (match) {
      const num = parseInt(match[1]!, 10);
      const title = match[2]!.trim();
      if (num > lastDetectedSection && num >= 1 && num <= 12) {
        return { section: num, title };
      }
    }
  }
  return null;
}

// ── Main streaming export ──────────────────────────────────────────────────────

export async function runPlannerStream(
  userMessage: string,
  history: PlannerStreamMessage[],
  onEvent: (event: PlannerStreamEvent) => void,
  signal: AbortSignal,
): Promise<void> {
  // ── Stage 1: Analyze Request ────────────────────────────────────────────────
  onEvent({ type: "stage_start", stage: 1, name: "Analyze Request" });

  const apiKey = sanitizeKey(process.env["OPENROUTER_API_KEY"]);

  // Perform fast regex-based intent classification
  let intent = classifyIntentFast(userMessage);

  onEvent({ type: "stage_complete", stage: 1 });

  // ── Stage 2: Classify Project ───────────────────────────────────────────────
  onEvent({ type: "stage_start", stage: 2, name: "Classify Project" });

  // For AMBIGUOUS messages without an API key, default to PROJECT
  // For AMBIGUOUS with API key, use LLM classification
  if (intent === "AMBIGUOUS") {
    if (apiKey) {
      try {
        const classifyMessages = [
          {
            role: "system",
            content: `Classify this user message as exactly one of: GREETING, CONVERSATION, or PROJECT.
GREETING = hello/hi/greetings only.
CONVERSATION = casual chat, questions about you, small talk.
PROJECT = any request to build, create, or develop a software product.
Reply with only the single word.`,
          },
          { role: "user", content: userMessage.slice(0, 500) },
        ];

        const response = await callOpenRouterConversational(
          classifyMessages,
          apiKey,
          signal,
        );
        const word = response.trim().toUpperCase();
        if (word === "GREETING" || word === "CONVERSATION" || word === "PROJECT") {
          intent = word as IntentType;
        } else {
          intent = "PROJECT";
        }
      } catch {
        intent = "PROJECT";
      }
    } else {
      intent = "PROJECT";
    }
  }

  onEvent({ type: "stage_complete", stage: 2 });

  // ── Non-project intent: conversational response ─────────────────────────────
  if (intent === "GREETING" || intent === "CONVERSATION") {
    if (!apiKey) {
      const fallback =
        intent === "GREETING"
          ? "Hello! Add your OPENROUTER_API_KEY in Replit Secrets to enable AI responses."
          : "To enable AI responses, add your OPENROUTER_API_KEY in Replit Secrets and restart the backend.";
      onEvent({ type: "conversation", content: fallback });
      return;
    }

    const conversationalMessages = [
      { role: "system", content: CONVERSATION_SYSTEM_PROMPT },
      ...history.slice(-4).map((m) => ({ role: m.role, content: m.content })),
      { role: "user", content: userMessage },
    ];

    try {
      const content = await callOpenRouterConversational(
        conversationalMessages,
        apiKey,
        signal,
      );
      onEvent({ type: "conversation", content });
    } catch {
      onEvent({
        type: "conversation",
        content: "Hello! How can I help you today?",
      });
    }
    return;
  }

  // ── PROJECT intent: run full 8-stage pipeline ────────────────────────────────

  if (!apiKey) {
    onEvent({
      type: "error",
      message:
        "The AI Planner requires an OPENROUTER_API_KEY in Replit Secrets. " +
        "Add it and restart the backend to generate architecture blueprints.",
    });
    return;
  }

  // ── Stages 3–7: Design via streaming LLM ────────────────────────────────────
  onEvent({ type: "stage_start", stage: 3, name: "Design Architecture" });

  const planMessages = [
    { role: "system", content: SYSTEM_PROMPT },
    ...history.slice(-6).map((m) => ({ role: m.role, content: m.content })),
    { role: "user", content: userMessage },
  ];

  let accumulated = "";
  let lastDetectedSection = 0;
  let currentStage = 3;
  let finalModel: string = PLANNER_MODELS[0] as string;

  const handleChunk = (chunk: string) => {
    accumulated += chunk;
    onEvent({ type: "content_chunk", text: chunk });

    // Detect new section boundaries
    const found = detectSectionInChunk(accumulated, lastDetectedSection);
    if (found && found.section !== lastDetectedSection) {
      lastDetectedSection = found.section;
      onEvent({ type: "section_detected", section: found.section, title: found.title });

      // Advance stages based on which section just appeared
      const targetStage = SECTION_TO_STAGE[found.section] ?? currentStage;
      if (targetStage > currentStage) {
        onEvent({ type: "stage_complete", stage: currentStage });
        currentStage = targetStage;
        onEvent({ type: "stage_start", stage: currentStage, name: PLANNER_STAGES[currentStage - 1]!.name });
      }
    }
  };

  let succeeded = false;

  for (let i = 0; i < PLANNER_MODELS.length; i++) {
    const model = PLANNER_MODELS[i]!;
    if (signal.aborted) break;
    if (i > 0) console.log(`[FALLBACK_ACTIVATED] switching to fallback model=${model} attempt=${i + 1}/${PLANNER_MODELS.length}`);
    try {
      const result = await callOpenRouterStream(
        model,
        planMessages,
        apiKey,
        handleChunk,
        signal,
      );
      finalModel = result.model as PlannerModel;
      succeeded = true;
      break;
    } catch (err) {
      if (signal.aborted) break;
      const msg = err instanceof Error ? err.message : String(err);
      const status = (err as { status?: number }).status;
      console.error(`[MODEL_FAILED] planner stream model=${model} attempt=${i + 1} error=${msg.slice(0, 120)}`);
      // Non-retryable: invalid API key
      if (status === 401 || status === 403) {
        onEvent({
          type: "error",
          message: `Invalid OpenRouter API key. Please check OPENROUTER_API_KEY in Replit Secrets.`,
        });
        return;
      }
      // Continue to next model
    }
  }

  if (!succeeded) {
    onEvent({
      type: "error",
      message: "All AI models in the fallback chain are currently unavailable. Please try again.",
    });
    return;
  }

  // Complete any remaining open stages
  if (currentStage < 7) {
    for (let s = currentStage; s <= 7; s++) {
      onEvent({ type: "stage_complete", stage: s });
    }
  } else {
    onEvent({ type: "stage_complete", stage: currentStage });
  }

  // ── Stage 8: Blueprint Finalization ─────────────────────────────────────────
  onEvent({ type: "stage_start", stage: 8, name: "Blueprint Finalization" });
  // Stage 8 completes in the route handler after DB persistence
  console.log(`[PLANNER_COMPLETED] model=${finalModel} contentLength=${accumulated.length}`);
  onEvent({
    type: "done",
    content: accumulated,
    model: finalModel,
  });
}
